spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/querydsl
    username: Kim
    password: 123123

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true




logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: trace